# Generated by Django 2.0 on 2017-12-11 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HobbyCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=250)),
                ('hobbycat_title', models.CharField(max_length=250)),
                ('hobbycat_logo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='HobbyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=10)),
                ('hobbyitem_title', models.CharField(max_length=250)),
                ('hobbyitem_dic', models.CharField(max_length=1000)),
                ('hobbycat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hobby.HobbyCat')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='hobbyitem',
            name='label_tag',
            field=models.ManyToManyField(to='hobby.Tags'),
        ),
    ]
