# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=1000)),
                ('publish', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=140)),
                ('image', models.ImageField(null=True, upload_to='upload_location')),
                ('content', models.TextField()),
                ('link', models.URLField(blank=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
