# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0002_auto_20171216_1242'),
        ('addpost', '0002_remove_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='hobbyitem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hobby.HobbyItem'),
            preserve_default=False,
        ),
    ]
